In [3]:
# 基础的东西 这一part貌似挺好滴
# from sp_functions import get_data
import pandas as pd
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import matplotlib as mpl

In [4]:
def get_data(name, cols=None, fmt=None, skipfooter=0):
    df = pd.read_csv(name, engine='python',skipfooter=skipfooter)
    df = df.set_index('Date')
    df.index = pd.to_datetime(df.index, format=fmt)
    if cols is None:
        return df
    else:
        return df[cols]
        
data = get_data("data-220020013.csv")
data = data.dropna(how='any')

In [5]:
# 1 用max return 限制weight sum为1 平均年度std为0.2
def cal_risk_contribution(w, cov):
    w = w[:, None]
    sigma_p = np.sqrt(np.matmul(np.matmul(w.T, cov), w)) #风险 控制在20%之内
    risk_contrib = w * np.matmul(cov, w) / sigma_p 
    risk_contrib_pct = risk_contrib / sigma_p
    return risk_contrib_pct.squeeze()


def record_results(weight, asset_return, port_val):
    asset_return_cum = (asset_return + 1).cumprod()
    port_return_cum = (asset_return_cum * weight).sum(axis=1)
    port_val_new = port_return_cum * port_val.iloc[-1, 0]
    port_val_new = port_val_new.to_frame()
    port_val_new.columns = port_val.columns
    port_val = port_val.append(port_val_new)
    return port_val


def cal_return(w):
    w = w[:, None]
    train_data1 = np.array(train_data)
    re = -np.sum(np.matmul(train_data1, w), axis=0)
    return re.squeeze()


def get_weight(cov):
    n_assets = len(cov)
    init_w = np.array([1 / n_assets] * n_assets)

    def opt(w, cov):
        return_all = cal_return(w)
        return return_all

    cons = [{
        'type': 'eq',
        'fun': lambda x: np.sum(x) - 1
    }, {
        'type': 'ineq',
        'fun': lambda x: -np.sqrt(np.matmul(np.matmul(x.T, cov), x)) + 0.05
    }]
    bounds = [[0, 1]] * n_assets
    res = minimize(opt,
                   init_w,
                   args=(cov, ),
                   constraints=cons,
                   method='SLSQP',
                   bounds=bounds)
    assert res.success
    return res.x


# 1）这个里面的cons设置有问题，sum权重是一，但是后面的std不是整个区间的（year=5），
#而要是一年的，又不可以简单/区间长度（5），因为不是年平均std小于20%是每一年都是小于20%，
#那是不是要写个函数还是咋样，我不会

In [33]:
data

,fund_1,fund_2,fund_3,fund_4,fund_5,fund_6,fund_7,fund_8,fund_9,fund_10
Date,,,,,,,,,,
2009-03-31,0.0290,0.0010,-0.1370,-0.1470,-0.0640,-0.1140,-0.1019,-0.0308,-0.1102,0.1067
2009-06-30,0.4160,0.4430,0.6600,0.6620,0.4750,0.4910,0.4290,0.3243,0.0381,-0.0405
2009-09-30,0.1920,0.2340,0.3050,0.1570,0.2740,0.1980,0.1004,0.2067,0.0066,0.0776
2009-12-31,-0.0020,-0.0020,0.1410,-0.0020,-0.0020,0.0560,-0.0106,0.0739,0.0207,0.0668
2010-03-31,0.0340,0.0190,0.0920,0.0460,0.0540,0.0180,-0.0079,0.0322,0.0091,-0.0242
2010-06-30,0.0290,0.0610,0.0940,0.0020,0.0500,0.0040,0.0750,0.0168,0.0278,0.1415
2010-09-30,0.1540,0.1620,0.1420,0.1910,0.1830,0.1430,0.0679,0.1220,-0.0025,0.0145
2010-12-31,0.0120,0.0020,-0.0440,0.0010,-0.0260,-0.0190,-0.0344,-0.0160,0.0173,0.0608
2011-03-31,-0.0260,-0.0580,-0.1470,-0.0900,-0.0730,-0.0490,-0.0510,-0.0593,0.0172,0.0085
2011-06-30,-0.0100,-0.0250,0.0150,0.0490,0.0260,-0.0270,-0.0154,-0.0047,0.0073,0.0494
2011-09-30,-0.0940,-0.0870,-0.0520,-0.0140,-0.0890,-0.1070,-0.0777,-0.0820,0.0087,0.1917
2011-12-31,-0.0240,-0.0400,-0.1350,-0.0810,-0.0850,-0.0730,-0.0375,-0.0685,0.0357,0.0489
2012-03-31,0.1270,0.1710,0.2000,0.1460,0.2110,0.1780,0.1030,0.0857,0.0363,0.0394
2012-06-30,-0.0060,-0.0190,0.0040,0.0310,0.0140,-0.0320,-0.0181,0.0360,0.0532,0.0391
2012-09-30,0.0810,0.0860,0.0960,0.1020,0.1070,0.0930,0.0820,0.0952,0.0221,0.0599
2012-12-31,0.0440,0.0380,0.0450,0.1300,0.0540,0.0520,0.0615,0.0325,0.0262,-0.0272
2013-03-31,-0.0490,-0.0390,-0.1580,-0.1250,-0.0790,0.0190,-0.0900,-0.0175,0.0173,-0.0274
2013-06-30,0.0180,-0.0060,-0.0070,-0.0170,-0.0310,0.0210,0.0839,0.0288,0.0518,-0.1548
2013-09-30,0.0130,-0.0110,-0.0450,-0.0840,-0.0430,0.1700,-0.0075,0.0093,-0.0858,0.1606
2013-12-31,0.1000,0.1230,0.2490,0.1310,0.1950,0.1630,0.0973,0.1453,0.0141,-0.1982
2014-03-31,0.0660,0.0978,0.1021,0.0537,0.0753,0.0360,0.0486,0.0074,0.0185,0.0424
2014-06-30,0.1683,0.1669,0.3572,0.2267,0.2292,0.1625,0.1991,0.1314,0.0491,0.0054
2014-09-30,0.0558,0.0424,0.1608,0.2216,0.0705,0.2127,0.0458,0.0749,0.0199,-0.0662
2014-12-31,0.0651,0.0393,0.1545,0.0904,0.1166,0.0370,0.0064,0.0256,0.0744,0.0167
2015-03-31,0.0297,0.0092,0.0804,0.0254,0.0198,0.0863,0.0405,0.0879,0.0288,-0.0309
2015-06-30,-0.0166,0.0023,0.0067,-0.0232,-0.0331,-0.0190,-0.0104,-0.0247,-0.0133,0.0133
2015-09-30,-0.0241,-0.0517,0.0458,0.0073,-0.0024,0.0867,-0.0281,0.0051,0.0457,-0.0166
2015-12-31,0.0099,0.0788,0.0582,0.0340,0.0218,0.0050,-0.0022,-0.0110,-0.0083,-0.0472
2016-03-31,-0.0368,-0.0241,-0.0739,-0.0312,-0.1075,-0.0923,-0.0176,-0.0528,0.0326,0.1569
2016-06-30,0.0631,0.0722,0.1110,0.0221,0.0593,0.0527,0.0468,0.0439,0.0148,0.0508
2016-09-30,0.0494,0.0565,0.0742,0.0663,0.0352,0.0283,0.0219,0.0539,0.0632,-0.0164
2016-12-31,-0.0348,-0.0173,-0.0300,-0.0886,-0.0697,-0.0441,-0.0310,-0.0460,0.0285,-0.1132
2017-03-31,0.1157,0.0949,0.1626,0.1296,0.1497,0.1223,0.0851,0.1114,-0.0113,0.0224
2017-06-30,0.0405,0.0147,0.0483,0.0550,0.0460,0.0403,0.0289,0.0377,0.0452,-0.0047
2017-09-30,0.0490,0.0323,-0.0148,0.0515,0.0254,0.0116,0.0208,0.0880,-0.0034,0.0314
2017-12-31,0.0902,0.0613,0.1891,0.1550,0.1423,0.1060,0.0396,0.0399,-0.0223,-0.0199
2018-03-31,-0.0487,-0.0523,-0.1200,-0.0528,-0.0800,-0.0429,-0.0181,-0.0323,0.0145,0.0496
2018-06-30,0.0254,0.0333,-0.0891,0.0042,-0.0260,-0.0054,0.0265,0.0223,-0.0055,-0.0196
2018-09-30,0.0225,0.0219,-0.0797,-0.0251,0.0214,0.0100,0.0128,-0.0218,0.0129,-0.0006
2018-12-31,-0.0064,0.0007,0.0128,0.0425,0.0703,-0.0550,0.0005,-0.0093,0.0495,0.0349
2019-03-31,0.0374,0.0293,0.0586,0.0594,0.0399,0.0538,0.0316,0.0423,0.0235,-0.0029
2019-06-30,0.0189,-0.0077,-0.0230,0.0273,0.0044,-0.0090,-0.1009,0.0449,0.0391,0.0870
2019-09-30,-0.0256,-0.0811,-0.0753,-0.0019,-0.0680,-0.0451,-0.0636,-0.0007,0.0228,0.1197
2019-12-31,0.0611,0.0604,0.0615,0.0672,0.0619,0.0854,0.0579,0.0308,0.0064,0.0377
2020-03-31,-0.2866,-0.3131,-0.2747,-0.2191,-0.3384,-0.2764,-0.2168,-0.1745,0.0420,0.1111
2020-06-30,0.2453,0.2335,0.2549,0.1665,0.1629,0.2481,0.1492,0.1583,0.0418,0.1101
2020-09-30,0.0636,0.1000,0.2218,0.0386,0.0754,0.0831,0.2219,0.0525,0.0000,0.0266

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 47 entries, 2009-03-31 to 2020-09-30
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   fund_1   47 non-null     float64
 1   fund_2   47 non-null     float64
 2   fund_3   47 non-null     float64
 3   fund_4   47 non-null     float64
 4   fund_5   47 non-null     float64
 5   fund_6   47 non-null     float64
 6   fund_7   47 non-null     float64
 7   fund_8   47 non-null     float64
 8   fund_9   47 non-null     float64
 9   fund_10  47 non-null     float64
dtypes: float64(10)
memory usage: 5.3 KB

In [15]:
rebal_days = ['2014/09/30','2015/09/30','2016/09/30','2017/09/30','2018/09/30','2019/09/30']
rebal_days = [pd.to_datetime(x) for x in rebal_days]
rebal_days

[Timestamp('2014-09-30 00:00:00'),
 Timestamp('2015-09-30 00:00:00'),
 Timestamp('2016-09-30 00:00:00'),
 Timestamp('2017-09-30 00:00:00'),
 Timestamp('2018-09-30 00:00:00'),
 Timestamp('2019-09-30 00:00:00')]

In [16]:
port_value = pd.DataFrame(index=[rebal_days[0]], data=[[100]], columns=["Risk Parity"])
port_value_eq = pd.DataFrame(index=[rebal_days[0]], data=[[100]], columns=["Equal Weight"])
port_value, port_value_eq

(            Risk Parity
 2014-09-30          100,
             Equal Weight
 2014-09-30           100)

In [20]:
for rebal_date, next_date in zip(rebal_days[:-1],rebal_days[1:]):
    print(rebal_date, next_date)
    break

2014-09-30 00:00:00 2015-09-30 00:00:00

In [27]:
train_start_date = rebal_date - pd.DateOffset(years=5)
train_start_date

Timestamp('2009-09-30 00:00:00')

In [26]:
train_data = data.loc[train_start_date:rebal_date]
train_data

,fund_1,fund_2,fund_3,fund_4,fund_5,fund_6,fund_7,fund_8,fund_9,fund_10
Date,,,,,,,,,,
2009-09-30,0.1920,0.2340,0.3050,0.1570,0.2740,0.1980,0.1004,0.2067,0.0066,0.0776
2009-12-31,-0.0020,-0.0020,0.1410,-0.0020,-0.0020,0.0560,-0.0106,0.0739,0.0207,0.0668
2010-03-31,0.0340,0.0190,0.0920,0.0460,0.0540,0.0180,-0.0079,0.0322,0.0091,-0.0242
2010-06-30,0.0290,0.0610,0.0940,0.0020,0.0500,0.0040,0.0750,0.0168,0.0278,0.1415
2010-09-30,0.1540,0.1620,0.1420,0.1910,0.1830,0.1430,0.0679,0.1220,-0.0025,0.0145
2010-12-31,0.0120,0.0020,-0.0440,0.0010,-0.0260,-0.0190,-0.0344,-0.0160,0.0173,0.0608
2011-03-31,-0.0260,-0.0580,-0.1470,-0.0900,-0.0730,-0.0490,-0.0510,-0.0593,0.0172,0.0085
2011-06-30,-0.0100,-0.0250,0.0150,0.0490,0.0260,-0.0270,-0.0154,-0.0047,0.0073,0.0494
2011-09-30,-0.0940,-0.0870,-0.0520,-0.0140,-0.0890,-0.1070,-0.0777,-0.0820,0.0087,0.1917
2011-12-31,-0.0240,-0.0400,-0.1350,-0.0810,-0.0850,-0.0730,-0.0375,-0.0685,0.0357,0.0489
2012-03-31,0.1270,0.1710,0.2000,0.1460,0.2110,0.1780,0.1030,0.0857,0.0363,0.0394
2012-06-30,-0.0060,-0.0190,0.0040,0.0310,0.0140,-0.0320,-0.0181,0.0360,0.0532,0.0391
2012-09-30,0.0810,0.0860,0.0960,0.1020,0.1070,0.0930,0.0820,0.0952,0.0221,0.0599
2012-12-31,0.0440,0.0380,0.0450,0.1300,0.0540,0.0520,0.0615,0.0325,0.0262,-0.0272
2013-03-31,-0.0490,-0.0390,-0.1580,-0.1250,-0.0790,0.0190,-0.0900,-0.0175,0.0173,-0.0274
2013-06-30,0.0180,-0.0060,-0.0070,-0.0170,-0.0310,0.0210,0.0839,0.0288,0.0518,-0.1548
2013-09-30,0.0130,-0.0110,-0.0450,-0.0840,-0.0430,0.1700,-0.0075,0.0093,-0.0858,0.1606
2013-12-31,0.1000,0.1230,0.2490,0.1310,0.1950,0.1630,0.0973,0.1453,0.0141,-0.1982
2014-03-31,0.0660,0.0978,0.1021,0.0537,0.0753,0.0360,0.0486,0.0074,0.0185,0.0424
2014-06-30,0.1683,0.1669,0.3572,0.2267,0.2292,0.1625,0.1991,0.1314,0.0491,0.0054
2014-09-30,0.0558,0.0424,0.1608,0.2216,0.0705,0.2127,0.0458,0.0749,0.0199,-0.0662

In [29]:
cov = train_data.cov().values
cov

array([[ 0.00545635,  0.00630149,  0.00903273,  0.00626639,  0.00782058,
         0.00573396,  0.00462285,  0.00487635,  0.00012963, -0.00155108],
       [ 0.00630149,  0.00763757,  0.01078325,  0.00714132,  0.00936387,
         0.00652432,  0.00529994,  0.00567186,  0.00020512, -0.0012836 ],
       [ 0.00903273,  0.01078325,  0.02019402,  0.01278083,  0.01456083,
         0.01019855,  0.00871917,  0.00934262,  0.00061393, -0.00253945],
       [ 0.00626639,  0.00714132,  0.01278083,  0.01092892,  0.00998948,
         0.00693399,  0.00584727,  0.00598446,  0.00064942, -0.00259992],
       [ 0.00782058,  0.00936387,  0.01456083,  0.00998948,  0.01229709,
         0.00814937,  0.00674399,  0.00744528,  0.00039446, -0.0022305 ],
       [ 0.00573396,  0.00652432,  0.01019855,  0.00693399,  0.00814937,
         0.00929451,  0.00481608,  0.0059324 , -0.00069275, -0.00228671],
       [ 0.00462285,  0.00529994,  0.00871917,  0.00584727,  0.00674399,
         0.00481608,  0.00520929,  0.00414831,  0.00052173, -0.00201692],
       [ 0.00487635,  0.00567186,  0.00934262,  0.00598446,  0.00744528,
         0.0059324 ,  0.00414831,  0.0054606 ,  0.00011787, -0.00213176],
       [ 0.00012963,  0.00020512,  0.00061393,  0.00064942,  0.00039446,
        -0.00069275,  0.00052173,  0.00011787,  0.00079036, -0.00098213],
       [-0.00155108, -0.0012836 , -0.00253945, -0.00259992, -0.0022305 ,
        -0.00228671, -0.00201692, -0.00213176, -0.00098213,  0.00838732]])

In [31]:
w_star = get_weight(cov)
w_star

array([0.00000000e+00, 1.39788684e-16, 3.48916105e-02, 1.33969461e-02,
       2.25991309e-16, 5.03512314e-01, 0.00000000e+00, 0.00000000e+00,
       2.20716860e-01, 2.27482270e-01])

In [34]:
asset_return = data.loc[rebal_date:next_date]
asset_return

,fund_1,fund_2,fund_3,fund_4,fund_5,fund_6,fund_7,fund_8,fund_9,fund_10
Date,,,,,,,,,,
2014-09-30,0.0558,0.0424,0.1608,0.2216,0.0705,0.2127,0.0458,0.0749,0.0199,-0.0662
2014-12-31,0.0651,0.0393,0.1545,0.0904,0.1166,0.0370,0.0064,0.0256,0.0744,0.0167
2015-03-31,0.0297,0.0092,0.0804,0.0254,0.0198,0.0863,0.0405,0.0879,0.0288,-0.0309
2015-06-30,-0.0166,0.0023,0.0067,-0.0232,-0.0331,-0.0190,-0.0104,-0.0247,-0.0133,0.0133
2015-09-30,-0.0241,-0.0517,0.0458,0.0073,-0.0024,0.0867,-0.0281,0.0051,0.0457,-0.0166

In [35]:
rebal_days[:-1]

[Timestamp('2014-09-30 00:00:00'),
 Timestamp('2015-09-30 00:00:00'),
 Timestamp('2016-09-30 00:00:00'),
 Timestamp('2017-09-30 00:00:00'),
 Timestamp('2018-09-30 00:00:00')]

In [18]:
for rebal_date, next_date in zip(rebal_days[:-1],rebal_days[1:]):
    train_start_date = rebal_date - pd.DateOffset(years=5)
    train_data = data.loc[train_start_date:rebal_date]
    cov = train_data.cov().values
    w_star = get_weight(cov)
    asset_return = data.loc[rebal_date:next_date]
    port_value = record_results(w_star, asset_return, port_value)
    w_eq = np.array([1/10]*10)
    port_value_eq = record_results(w_eq, asset_return, port_value_eq)

In [19]:
train_start_date

Timestamp('2013-09-30 00:00:00')

In [7]:
sigma_p_eq = np.sqrt(np.matmul(np.matmul(w_eq.T,cov), w_eq))
sigma_p = np.sqrt(np.matmul(np.matmul(w_star.T,cov), w_star))

# 问题是只配了两只基金。。。

In [9]:
sigma_p, sigma_p_eq

(0.050000000001191355, 0.052331920050677265)

In [10]:
# max 夏普比率
def cal_return2(w,cov):
    w = w[:,None]
    train_data1 = np.array(train_data)
    sigma_p = np.sqrt(np.matmul(np.matmul(w.T,cov), w))
    re = (-1)*((np.sum(np.matmul(train_data1,w),axis=0))/(sigma_p))
    return re.squeeze()
  #2）这里就是我问你的分数怎么处理，我不知道直接这样处理行不行，你说后面的method要改，但是我查了资料也不知道怎么改。
def get_weight2(cov):
    n_assets = len(cov)
    init_w = np.array([1/n_assets] * n_assets)
    def opt(w, cov):
        return_all = cal_return2(w, cov)
        return return_all
    cons = [{'type':'eq', 'fun':lambda x:np.sum(x)-1},{'type':'ineq', 'fun':lambda x:-np.sqrt(np.matmul(np.matmul(x.T,cov), x))+0.05}]
    bounds = [[0, 1]]*n_assets
    res = minimize(opt, init_w, args=(cov,),constraints=cons, method='SLSQP',bounds=bounds)
    assert res.success
    return res.x

for rebal_date, next_date in zip(rebal_days[:-1],rebal_days[1:]):
    train_start_date = rebal_date - pd.DateOffset(years=5)
    train_data = data.loc[train_start_date:rebal_date]
    cov = train_data.cov().values
    w_star = get_weight2(cov)
    asset_return = data.loc[rebal_date:next_date]
    port_value2 = record_results(w_star, asset_return, port_value)
    w_eq = np.array([1/10]*10)
    port_value_eq2 = record_results(w_eq, asset_return, port_value_eq)

sigma_p_eq2 = np.sqrt(np.matmul(np.matmul(w_eq.T,cov), w_eq))
sigma_p2 = np.sqrt(np.matmul(np.matmul(w_star.T,cov), w_star))
# 问题：只配了四只并且std超级低

In [11]:
sigma_p2, sigma_p_eq2

(0.024035375851835086, 0.052331920050677265)

In [ ]:
# 后面不用看
def Max_Diversification_Ratio(n ,cov):
    def Get_Diversification_Ratio(w):
       cov_mdr = np.asmatrix(cov)
       temp = np.dot(w,cov_mdr.diagonal().T)
       sigma_p = np.sqrt(np.dot(np.dot(w.T,cov_mdr), w))
       return sigma_p/temp
    init_w = np.array([1/n]*n, ndmin=2)
    bounds = [[0, 1]]*n
    cons = [{'type':'eq', 'fun': lambda x: np.sum(x)-1}]                    
    res = minimize(Get_Diversification_Ratio, init_w, constraints = cons, bounds=bounds)
    return res.x

for rebal_date, next_date in zip(rebal_days[:-1],rebal_days[1:]):
      train_start_date = rebal_date - pd.DateOffset(years=5)
      train_data = data.loc[train_start_date:rebal_date]
      cov = train_data.cov().values
      w_star = Max_Diversification_Ratio(10 ,cov)
      asset_return = data.loc[rebal_date:next_date]
      port_value3 = record_results(w_star, asset_return, port_value)
      w_eq = np.array([1/10]*10)
      port_value_eq3 = record_results(w_eq, asset_return, port_value_eq)

sigma_p_eq3 = np.sqrt(np.matmul(np.matmul(w_eq.T,cov), w_eq))
sigma_p3 = np.sqrt(np.matmul(np.matmul(w_star.T,cov), w_star))

def global_minimum_variance(data, long = 1):
    def GMV_function(w,corr):
        obj_function = np.dot(w.T,np.dot(corr,w))
        return obj_function
    corr = data.corr()
    n = corr.shape[0]
    w = np.ones(n) /n
    cons = ({'type': 'eq', 'fun': lambda x: 1 - sum(x)})
    bnds = [(0,0.1) for i in w]
    if long == 1:
        res = minimize(GMV_function, x0 = w, args = (corr), method = 'SLSQP', constraints = cons,bounds = bnds, tol = 1e-30)
    else:
        res = minimize(GMV_function, x0 = w, args = (corr), method = 'SLSQP', constraints = cons, tol = 1e-30)
    return res.x

for rebal_date, next_date in zip(rebal_days[:-1],rebal_days[1:]):
      train_start_date = rebal_date - pd.DateOffset(years=5)
      train_data = data.loc[train_start_date:rebal_date]
      cov = train_data.cov().values
      w_star4 = Max_Diversification_Ratio(10 ,cov)
      asset_return = data.loc[rebal_date:next_date]
      port_value4 = record_results(w_star, asset_return, port_value)
      w_eq = np.array([1/10]*10)
      port_value_eq4 = record_results(w_eq, asset_return, port_value_eq)

sigma_p_eq4 = np.sqrt(np.matmul(np.matmul(w_eq.T,cov), w_eq))
sigma_p4 = np.sqrt(np.matmul(np.matmul(w_star4.T,cov), w_star4))